export class Add {
    model:string;
    brand:string;
    image:string;
    devicecolor:string;
    addedincart=false;
    product_details:string;
    price:number;
    id:number;
    constructor(model:string,brand:string,image:string,devicecolor:string,price:number,product_details:string,id:number){
        this.model=model;
        this.brand=brand;
        this.image=image;
        this.price=price;
        this.product_details=product_details;
        this.id=id;
        
    }
}
export class Phones extends Add{
    screen:string;
    ram:string;
    processor:string;
    
    constructor(
    model:string,
    brand:string,
    image:string,
    devicecolor:string,
    price:number,
    product_details:string,
    screen:string,
    ram:string,
    processor:string,
    id){
super(model,brand,image,devicecolor,price,product_details,id);
this.processor=processor;
this.ram=ram;
this.screen=screen;
    }
}
export class tablets extends Add{
    processor:string;
    internalmemory:string;
    screensize:string;
    ram:string;
    constructor(
        model:string,
        brand:string,
        image:string,
        devicecolor:string,
        price:number,
        product_details:string,
    processor:string,
    internalmemory:string,
    screensize:string,
    ram:string,
    id
    ){
        super(model,
brand,
image,
devicecolor,
price,
product_details,
id);
this.processor=processor;
this.internalmemory=internalmemory;
this.screensize=screensize;
this.ram=ram;
    }
}
export class TV extends Add{
    resolution:string;
    quality:string;
    screentype:string;
    constructor(model:string,
    brand:string,
    image:string,
    devicecolor:string,
    price:number,
    product_details:string,
    resolution:string,
    quality:string,
    screentype:string,
    id
    ){
        super(model,
brand,
image,
devicecolor,
price,
product_details,
id);
this.resolution=resolution;
this.quality=quality;
this.screentype=screentype;    
}
    
}

export class wears extends Add{
    resolution:string;
    storage:string;
    ram:string;
    screensize:string;
    constructor(model:string,
    brand:string,
    image:string,
    devicecolor:string,
    price:number,
    product_details:string,
    resolution:string,
    storage:string,
    screensize:string,
    ram:string,
    id
    ){
        super(model,
brand,
image,
devicecolor,
price,
product_details,
id);
this.resolution=resolution;
this.storage=storage;
this.ram=ram;
this.screensize=screensize;
    }
    
}